[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"

# Edge Functions Configuration
[[edge_functions]]
  path = "/*"
  function = "meta-handler"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self' https://*.supabase.co https://*.bolt.host; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://*.bolt.host https://connect.facebook.net https://www.googletagmanager.com https://www.facebook.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: blob: https://*.supabase.co https://images.pexels.com https://*.cloudfront.net https://*.bolt.host https://www.facebook.com; connect-src 'self' https://*.supabase.co wss://*.supabase.co https://*.bolt.host https://www.facebook.com; worker-src 'self' blob:;"